services:
  - postgres:latest

variables:
  POSTGRES_DB: "MaarchCourrier"
  POSTGRES_USER: maarch
  POSTGRES_PASSWORD: ""

stages:
  - test

before_script:
  - apt-get update > /dev/null
  - apt-get install apt-utils -yqq > /dev/null
  - bash ci/docker_install_mail_server.sh > /dev/null
  - bash ci/docker_install_php.sh > /dev/null
  - pear channel-discover pear.maarch.org
  - pear install maarch/CLITools-0.3.1


job_php-7.0:
  image: php:7.0-apache
  stage: test
  script:
    - mkdir -p /opt/maarch/docservers/indexes/{letterbox_coll,attachments_coll,version_attachments_coll}
  only:
    - develop
