services:
  - postgres:latest

variables:
  POSTGRES_DB: "MaarchCourrier"
  POSTGRES_USER: maarch
  POSTGRES_PASSWORD: ""

stages:
  - test

before_script:
  - pear channel-discover pear.maarch.org
  - apt-get update > /dev/null
  - apt-get install apt-utils -yqq > /dev/null
  - apt-get install -yqq libc-client-dev  > /dev/null 
  - apt-get install -yqq libkrb5-dev  > /dev/null
  - rm -r /var/lib/apt/lists/*
  - bash ci/docker_install_php.sh > /dev/null

job_php-7.0:
  image: php:7.0-apache
  stage: test
  script:
    - mkdir -p /opt/maarch/docservers/indexes/{letterbox_coll,attachments_coll,version_attachments_coll}
  only:
    - develop
