<?php
/*
 * Copyright (C) 2015 Maarch
 *
 * This file is part of Maarch.
 *
 * Maarch is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Maarch is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Maarch. If not, see <http://www.gnu.org/licenses/>.
 */
namespace Maarch\Http\Errors;
/**
 * Base class for http problems
 * 
 */
class HttpProblem
{
    /**
     * A URI reference that identifies the problem type.
     * 
     * RFC7807 specification encourages that, when
     * dereferenced, it provide human-readable documentation for the
     * problem type (e.g., using HTML [W3C.REC-html5-20141028]). When
     * this member is not present, its value is assumed to be
     * "about:blank".
     * 
     * @see https://tools.ietf.org/html/rfc7807#section-3.1
     * 
     * @var string 
     */
    protected $type;

    /**
     * A short, human-readable summary of the problem type.
     * 
     * It SHOULD NOT change from occurrence to occurrence of the
     * problem, except for purposes of localization (e.g., using
     * proactive content negotiation)
     * 
     * @see https://tools.ietf.org/html/rfc7807#section-3.1
     * 
     * @var string 
     */
    protected $title;

    /**
     * The HTTP status code generated by the origin server for this occurrence of the problem.
     * 
     * @see https://tools.ietf.org/html/rfc7807#section-3.1
     * 
     * @var integer
     */
    protected $status;

    /**
     * A human-readable explanation specific to this occurrence of the problem.
     * 
     * @see https://tools.ietf.org/html/rfc7807#section-3.1
     * 
     * @var string
     */
    protected $detail;

    /**
     * A URI reference that identifies the specific occurrence of the problem. 
     * 
     * It may or may not yield further information if dereferenced.
     * 
     * @see https://tools.ietf.org/html/rfc7807#section-3.1
     * 
     * @var string
     */
    protected $instance;

    /**
     * Returns the type of the problem.
     *  
     * @return string 
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Returns the title of the problem.
     * 
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Returns the HTTP status code generated by the origin server for this occurrence of the problem.
     * 
     * @return integer
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Returns a human-readable explanation specific to this occurrence of the problem.
     * 
     * @return string
     */
    public function getDetail()
    {
        return $this->detail;
    }

    /**
     * Returns the URI of instance
     * 
     * @return string
     */
    public function getInstance()
    {
        return $this->instance;
    }

}